config/routes.rb
Rails.application.routes.draw do
  resources :groceries
  devise_for :models
  root to: 'pages#home'
  devise_for :views
  devise_for :users
  get 'groceries/index'
  # root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grocery.rb
class Grocery < ApplicationRecord
  belongs_to :user
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  before_action :set_grocery, only: %i[ show edit update destroy ]

  # GET /groceries or /groceries.json
  def index
    @groceries = Grocery.all
  end

  # GET /groceries/1 or /groceries/1.json
  def show
  end

  # GET /groceries/new
  def new
    @grocery = Grocery.new
  end

  # GET /groceries/1/edit
  def edit
  end

  def allowed_input
    @grocery = Grocery.new(grocery_params)
    allowed_grocery_name = !@grocery.name.match(/^[a-zA-Z\d\s]*$/) || @grocery.name.empty?
    positive_quantity = @grocery.quantity.to_i <= 0
    allowed_grocery_name || positive_quantity
  end

  # POST /groceries or /groceries.json
  def create
    @grocery = Grocery.new(grocery_params)
    respond_to do |format|
      if allowed_input
        format.html { redirect_to @grocery, notice: "Grocery was NOT successfully created." }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      elsif @grocery.save
        format.html { redirect_to @grocery, notice: "Grocery was successfully created." }
        format.json { render :show, status: :created, location: @grocery }
      else
        format.html { redirect_to @grocery, notice: "Grocery was not successfully created." }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groceries/1 or /groceries/1.json
  def update
    respond_to do |format|
      if allowed_input
        format.html { redirect_to @grocery, notice: "Grocery was NOT successfully updated." }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      elsif @grocery.update(grocery_params)
        format.html { redirect_to @grocery, notice: "Grocery was successfully updated." }
        format.json { render :show, status: :ok, location: @grocery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @grocery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groceries/1 or /groceries/1.json
  def destroy
    @grocery.destroy
    respond_to do |format|
      format.html { redirect_to groceries_url, notice: "Grocery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grocery
      @grocery = Grocery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grocery_params
      params.require(:grocery).permit(:name, :quantity, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/groceries/_form.html.erb
<%= form_with(model: grocery) do |form| %>
  <% if grocery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

      <ul>
        <% grocery.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groceries/edit.html.erb
<h1>Editing Grocery</h1>

<%= render 'form', grocery: @grocery %>

<%= link_to 'Show', @grocery %> |
<%= link_to 'Back', groceries_path %>

app/views/groceries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groceries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groceries.each do |grocery| %>
      <tr>
        <td><%= grocery.name %></td>
        <td><%= grocery.quantity %></td>
        <td><%= grocery.user_id %></td>
        <td><%= link_to 'Show', grocery %></td>
        <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
        <td><%= link_to 'Destroy', grocery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grocery', new_grocery_path %>
<%= link_to 'Back to home', root_path %>

app/views/groceries/new.html.erb
<h1>New Grocery</h1>

<%= render 'form', grocery: @grocery %>

<%= link_to 'Back', groceries_path %>

app/views/groceries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @grocery.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @grocery.quantity %>
</p>

<p>
  <strong>User:</strong>
  <%= @grocery.user_id %>
</p>

<%= link_to 'Edit', edit_grocery_path(@grocery) %> |
<%= link_to 'Back', groceries_path %>

app/views/home/index.html.erb
<h1>Hello world</h1>

<%= button_to 'Login', 'auth/auth0', method: :post %>

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PentalogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to homeapp</h1>

<p>
	<strong>Welcome:</strong>
	<% if current_user %>
		<%= current_user.email %>
	<% else %>
		<%= "Stranger" %>
	<% end %>
</p>

<% if current_user %>
	<%= link_to 'Sign out', destroy_user_session_path,
	method: :delete %>
	<%= link_to 'Add a grocery', new_grocery_path %>
	<%= link_to 'Show current user groceries', groceries_path %>
<% else %>
<%= link_to 'Sign up', new_user_registration_path %>

<% link_to 'Sign in', new_user_session_path %>
<% end %>